version: "3"
services:
  mrdoc:
    build: .
    image: mrdoc-uwsgi:1.0
    container_name: mrdoc
    restart: always
    volumes:
      - ./config/doc:/app/MrDoc/config  # 请注意修改 /path/to/you/dir 为您要存储mrdoc数据的绝对路径.
      - ./data/media:/app/MrDoc/media    # 同上
      - ./config/uwsgi/uwsgi.ini:/etc/uwsgi/uwsgi.ini
    environment:
      - TZ=Asia/Shanghai
      ##### 以下注释项为可选变量
      - LISTEN_PORT=10086
      - CREATE_USER=1       # 0 不创建管理员用户, 1 创建管理员用户,默认是1
      - USER=admin     # 自定义管理员用户名
      - MM=1                # 自定义管理员密码，默认已使用随机密码，请修改start.sh启用
     # - UWSGI_INI=/app/MrDoc/uwsgi.ini

###### 如果默认用户密码,以及变量添加用户密码无法登录,请参考:https://www.mrdoc.fun/project-1/doc-242/
    # ports:
    #   - "10086:10086"
    networks:
        default:
        internal:

    depends_on:
      - mysql

  nginx:
    image: nginx:1.17
    restart: always
    volumes:
      - ./config/nginx/http.conf:/etc/nginx/conf.d/default.conf
      - ./static/:/app/MrDoc/static/  
      - ./data/media/:/app/MrDoc/media/  
    ports:
      - 8080:80

    networks:
        default:
    depends_on:
      - mrdoc
   
  mysql:
    image: mysql:5.7
    container_name: mysql-with-mrdoc    # 这里名字不要修改,否则无法连接数据库.如果修改,请注意自行更改mrdoc的配置文件.
    restart: always
    volumes:
      - ./data/mysql:/var/lib/mysql # 请注意修改 /path/to/you/dir 为您要存储mysql数据的目录绝对路径.
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=adminp
      - MYSQL_DATABASE=mrdoc
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    # expose:
    #   - "3306"
    # ports:
    #   - "63306:3306"  # 如果不需要外部连接mysql,可注释此行+上一行.
    networks:
      internal:
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"


# Volumes for persisting data, see https://docs.docker.com/engine/admin/volumes/volumes/
#volumes:
#  mrdoc-data:
#    driver: local
#  mysql-data:
#    driver: local

networks:
    default:
    internal:
        internal: true